# Generated by Django 6.0.2 on 2026-02-19 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='student',
        ),
    ]
